display_name = "Jopious"
authors = "Pepituwu, Lenoch"
version = "1.0.0"
description = """
Jopious over Captain Falcon's c02 costume. Comes with a Model Import for Jopious himself. Also comes with UI, Voice, and Name.
"""
category = "Fighter"
